# .github/workflows/wake_up.yml
name: Wake up periodically
on:
  schedule:
    - cron: '0 0 */5 * *' # 매 5일마다 실행, 자정에 실행
  workflow_dispatch: # 수동 실행용
jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send request
        run: |
          curl --request POST --url https://apxnfdywvfflfkbkwxdi.supabase.co/functions/v1/rapid-function \
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}' \
          --header 'Content-Type: application/json' \
          --data '{"name": "Github Actions"}'
